version: 0.2

phases:
  pre_build:
    commands:
      - aws cloudformation package --template-file cf-templates/template.yaml --s3-bucket $S3_BUCKET --output-template-file template-output.yaml
      - aws s3 sync cf-templates/ s3://$S3_BUCKET/

artifacts:
  files: # All the files which makes out of the build stage and shall be forwarded to the next stage are mentioned here. Every other file is no more available in the pipeline
    - template-output.yaml
    - config.json
