AWSTemplateFormatVersion: "2010-09-09"

Description: "Template"

Resources:

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.eu-central-1.amazonaws.com/io.codepipeline.demo-ci/vpc.yaml"
      Parameters:
        VPCName: "TEST-VPC"
